version: '3.1'

services:
  db:
    image: postgres
    container_name: veiculosGerenciamento
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      restart: always
    ports:
      - "5432:5432"